name: trestle
author: Emil Persson <emil.n.persson@gmail.com>
homepage: https://github.com/dart-bridge/trestle
version: 0.1.0
environment:
  sdk: '>=1.11.0 <2.0.0'
description: Database gateway and ORM
dev_dependencies:
  test: any
